apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: covid-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: covid-frontend
                port:
                  number: 3000
          - path: /recovery
            pathType: Prefix
            backend:
              service:
                name: covid-frontend
                port:
                  number: 3000
          - path: /register
            pathType: Prefix
            backend:
              service:
                name: covid-frontend
                port:
                  number: 3000
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: covid-frontend
                port:
                  number: 3000
          - path: /logout
            pathType: Prefix
            backend:
              service:
                name: covid-frontend
                port:
                  number: 3000
          - path: /home
            pathType: Prefix
            backend:
              service:
                name: covid-frontend
                port:
                  number: 3000
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: covid-frontend
                port:
                  number: 3000
          - path: /compare
            pathType: Prefix
            backend:
              service:
                name: covid-frontend
                port:
                  number: 3000
          - path: /myuser
            pathType: Prefix
            backend:
              service:
                name: covid-frontend
                port:
                  number: 3000
          - path: /plot
            pathType: Prefix
            backend:
              service:
                name: covid-frontend
                port:
                  number: 3000
          - path: /compare-strategies
            pathType: Prefix
            backend:
              service:
                name: covid-frontend
                port:
                  number: 3000
          - path: /countryinterest
            pathType: Prefix
            backend:
              service:
                name: covid-frontend
                port:
                  number: 3000
          - path: /countrylistreport
            pathType: Prefix
            backend:
              service:
                name: covid-frontend
                port:
                  number: 3000
          - path: /paises
            pathType: Prefix
            backend:
              service:
                name: covid-frontend
                port:
                  number: 3000
          - path: /static
            pathType: Prefix
            backend:
              service:
                name: covid-frontend
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: covid-api
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: covid-api
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
spec:
  controller: k8s.io/ingress-nginx
