apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: covid-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: covid-frontend
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: covid-api
                port:
                  number: 8080
