version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.2.0
  terraform: circleci/terraform@2.1.0

jobs:
  base_job:
    docker:
      - image: cimg/base:2021.07
    steps:
        - azure-cli/install
        - run:
            command: az -v
            name: Verify Azure CLI is installed

workflows:
  plan_apply:
    jobs:
      - base_job
