version: 2.1

orbs:
#  azure-cli: circleci/azure-cli@1.2.0
  terraform: circleci/terraform@2.1.0

jobs:
  job:
    docker:
      - image: cimg/base:2021.07
    steps:
      - run:
          name: Update PATH and Define Environment Variable at Runtime
          command: |
            echo 'export ARM_CLIENT_ID=$AZURE_SP' >> $BASH_ENV
            echo 'export ARM_CLIENT_SECRET=$AZURE_SP_PASSWORD' >> $BASH_ENV
            echo 'export ARM_SUBSCRIPTION_ID=$AZURE_SUB' >> $BASH_ENV
            echo 'export ARM_TENANT_ID=$AZURE_TENANT' >> $BASH_ENV
            echo 'export TF_VAR_Azure_AppID=$AZURE_SP' >> $BASH_ENV
            echo 'export TF_VAR_Azure_PW=$AZURE_SP_PASSWORD' >> $BASH_ENV
      - checkout
      - terraform/install
#        - azure-cli/install
#        - azure-cli/login-with-service-principal
      - terraform/init
#            path: .
#        - terraform/validate:
#            path: .
#        - terraform/fmt:
#            path: .
      - terraform/plan
          backend_config: resource_group_name=$SA_RG, storage_account_name=$SA_NAME, container_name=$SA_CNT_NAME, key=$SA_KEY
#            path: .
#        - terraform/apply:
#            path: .
#        - terraform/destroy:
#            path: .

workflows:
  workflow:
    jobs:
      - job
