version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.2.0
  terraform: circleci/terraform@2.1.0

jobs:
  base_job:
    docker:
      - image: cimg/base:2021.07 

workflows:
  plan_apply:
    jobs:
      - base_job
