version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.2.0
  terraform: circleci/terraform@2.1.0

jobs:
  azure_cli_install:
    docker:
      - image: cimg/base:2021.07
    steps:
        - azure-cli/install
        
  azure_cli_login:
    docker:
      - image: cimg/base:2021.07
    steps:
        - azure-cli/login-with-service-principal

workflows:
  workflow:
    jobs:
      - azure_cli_install
      - azure_cli_login:
          requires: 
            - azure_cli_install
