version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.2.0
  terraform: circleci/terraform@2.1.0

jobs:
  job:
    docker:
      - image: cimg/base:2021.07
    steps:
        - azure-cli/install
        - azure-cli/login-with-service-principal
        - checkout
        - terraform/init:
            path: .
        - terraform/validate:
            path: .
        - terraform/fmt:
            path: .
        - terraform/plan:
            path: .
        - terraform/apply:
            path: .
        - terraform/destroy:
            path: .

workflows:
  workflow:
    jobs:
      - job
