version: 2.1

orbs:
  terraform: circleci/terraform@2.1.0
  kubernetes: circleci/kubernetes@0.12.0
  azure-aks: circleci/azure-aks@0.2.1

jobs:
  setup_envvars:
    docker:
      - image: cimg/base:2021.07
    steps:
      - run:
          name: Update PATH and Define Environment Variable at Runtime
          command: |
            echo 'export ARM_CLIENT_ID=$AZURE_SP' >> $BASH_ENV
            echo 'export ARM_CLIENT_SECRET=$AZURE_SP_PASSWORD' >> $BASH_ENV
            echo 'export ARM_SUBSCRIPTION_ID=$AZURE_SUB' >> $BASH_ENV
            echo 'export ARM_TENANT_ID=$AZURE_TENANT' >> $BASH_ENV
            echo 'export TF_VAR_Azure_AppID=$AZURE_SP' >> $BASH_ENV
            echo 'export TF_VAR_Azure_AppIDPW=$AZURE_SP_PASSWORD' >> $BASH_ENV
            echo 'export TF_VAR_Azure_SQLADMIN=$AZURE_DB_ADMIN' >> $BASH_ENV
            echo 'export TF_VAR_Azure_SQLADMINPW=$AZURE_DB_ADMIN_PW' >> $BASH_ENV

  infra_creation:
    docker:
      - image: cimg/base:2021.07
    steps:
      - checkout
      - terraform/install
      - terraform/apply:
          backend_config: "storage_account_name=$SA_NAME, container_name=$SA_CNT_NAME, key=$SA_KEY, resource_group_name=$SA_RG"

  infra_deletion:
    docker:
      - image: cimg/base:2021.07
    steps:
      - checkout
      - terraform/install
      - terraform/destroy:
          backend_config: "storage_account_name=$SA_NAME, container_name=$SA_CNT_NAME, key=$SA_KEY, resource_group_name=$SA_RG"

  build-api-image:
    machine: true
    steps:
      - checkout
      - run: docker build -t santiagovarela86/k8s_repository_covid-api:latest covid-api
      - run: |
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
          docker push santiagovarela86/k8s_repository_covid-api:latest          

  create-k8s-resources:
    executor: azure-aks/default
    steps:
      - checkout
      - azure-aks/update-kubeconfig-with-credentials:
          resource-group: COVIDDEMO
          cluster-name: covid-aks
          install-kubectl: true
          perform-login: true
      - kubernetes/create-or-update-resource:
          resource-file-path: k8s_namespace.yml
      - kubernetes/create-or-update-resource:
          resource-file-path: covid-api/k8s_deployment.yml
          namespace: covid-k8s
      - run: |
          kubectl set env deployment/covid-api signing_key=asdasdasd

workflows:
  workflow:
    jobs:
      - setup_envvars
      - infra_creation:
          requires:
            - setup_envvars
#      - build-api-image:
#          requires:
#            - infra_creation
      - create-k8s-resources:
          requires:
            - infra_creation
#      - infra_deletion:
#          requires:
#            -  create-k8s-resources
