apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-api
  labels:
    app: covid-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid-api
  template:
    metadata:
      labels:
        app: covid-api
    spec:
      containers:
      - name: covid-api
        image: santiagovarela86/k8s_repository_covid-api:latest
        command: ["java"]
        args: ["-jar", "/java/application.jar"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: covid-api
spec:
  type: LoadBalancer
  selector:
    app: covid-api
  ports:
    - protocol: TCP
      name: https
      port: 443
      targetPort: 8080
