apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-api-deployment
  labels:
    app: covid-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid-api
  template:
    metadata:
      labels:
        app: covid-api
    spec:
      containers:
      - name: covid-api
        image: santiagovarela86/repository_covid-api:latest
        ports:
        - containerPort: 80
