apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-api
  labels:
    app: covid-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid-api
  template:
    metadata:
      labels:
        app: covid-api
    spec:
      containers:
      - name: covid-api
        image: santiagovarela86/k8s_repository_covid-api:latest
        #command: ["bash ./java/wait-for-it.sh covid-sql-devops-playground.database.windows.net:1433 -s -t 600 -- java -jar /java/application.jar"]
        command: ["java"]
        args: ["-jar", "/java/application.jar"]
        ports:
        - containerPort: 80
