apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-frontend
  labels:
    app: covid-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid-frontend
  template:
    metadata:
      labels:
        app: covid-frontend
    spec:
      containers:
      - name: covid-frontend
        image: santiagovarela86/k8s_repository_covid-frontend:latest
        command: ["npm"]
        args: ["start"]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: covid-frontend
spec:
  type: LoadBalancer
  selector:
    app: covid-frontend
  ports:
    - protocol: TCP
      name: https
      port: 443
      targetPort: 3000
